Create a file named `HomeController` which resolves the base URL `/`:

[source,java]
.src/main/java/example/micronaut/HomeController.java
----
include::{sourceDir}/src/main/java/example/micronaut/HomeController.java[]
----

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression to allow access to authenticated and unauthenticated users.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate a class as a Micronaut's controller.
<3> You can specify the HTTP verb for which a controller's action responds to. To respond to a GET request, use `io.micronaut.http.annotation.Get`
<4> Use https://docs.micronaut.io/latest/api/io/micronaut/views/View.html[View] annotation to specify which template would you like to render the response against.
<5> If you are authenticated, you can use the `java.security.Principal` as a parameter type. For parameters which maybe null, use `javax.annotation.Nullable`.

== Login Form

Next, create `LoginAuthController` which renders the login form.

[source,groovy]
.src/main/java/example/micronaut/LoginAuthController.java
----
include::{sourceDir}/src/main/java/example/micronaut/LoginAuthController.java[]
----

<1> Annotate with `io.micronaut.security.Secured` to configure security access. Use `isAnonymous()` expression for anonymous access.
<2> Annotate with `io.micronaut.http.annotation.Controller` to designate a class as a Micronaut's controller.
<3> Responds to GET requests at `/login/auth`
<4> Use https://docs.micronaut.io/latest/api/io/micronaut/views/View.html[View] annotation to specify which template would you like to render the response against.
<5> Responds to GET requests at `/login/authFailed`